services:
  warehouse:
    image: postgres:13  #de que imagen vamos a sacar
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./semana1:/var/lib/postgresql/data:rw" # LOS DOS PUNTOS SEAPANRA. PRIMERO MI DIRECCIÓN ACTUAL : DIRECCION DEL DIRECTORIO.  RW son los permisos
    ports:
      - "5432:5432"
  warehouseui:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - "./warehouse_ui_data:/var/lib/pgadmin"
    ports:
      - "8080:80"
    
  scheduler:
    image: mageai/mageai
    volumes:
      - "./scheduler_data:/home/src:rw"
    ports:
      - "6789:6789"
    command: /app/run_app.sh mage start scheduler
